### ISSUE TITLE
[RFC0001] Reorder Google OCR Output

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/Requests#2]
# [RFC0001] Reorder Google OCR Output

<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

*Please add ref in specified format into `RFC` title, e.g `[RFC9999]` if corresponding RFW is `[RFW9999]`.*

*Please add into this `RFC` and related `PR's` titles `[RFC_id]` e.g `[RFC_9999]`.*

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

**BDRC S3** - Google OCR output is stored as received (JSON response) in an AWS S3.  
**JSON Response** \- The output of Google OCR is a JSON file with the text and box coordinates. See [this example](https://github.com/OpenPecha/OCR-Helper-Scripts/files/9110159/I2PD18490.zip).
**Pecha** - Files in the OpenPecha archive.
**Layer via cut** \- parts of the base text in an OPF are cut out of the text and transfered into a layer file. The concept is similar to creating layers via cut in Photoshop

<h2 id="summary">Summary</h2>

The google OCR response content boxes wise text and coordinate info as well as the text of the whole page generated by their algorithm. We found some order issues as we go through those whole page texts. We prepared a post-processing module to handle the jumbled text issue. We have prepared a pipeline to update all the existing google OCRed opfs.

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

*This section provides a detailed technical overview of the work. The design is explained with enough depth and detail to make it clear how:*

Inorder to full fill the request, we have to update our [Openpecha toolkit google OCR formatter](https://github.com/OpenPecha/Toolkit/blob/master/openpecha/formatters/google_ocr.py). The pipeline to update our existing opfs is in [OCR-Helper-script repo](https://github.com/OpenPecha/OCR-Helper-Scripts).

Steps to reorder the boxes are following:

<em>

- The centroid of boxes is calculated
- The boxes are sorted according to the y coordinate of the centroid
- The average height of the boxes is calculated
- The boxes are grouped according to which lines they belong using the average height
- The boxes belonging to a group are sorted according to the x coordinate of the centroid. 
- The text of the boxes are then extracted to construct the reordered base text.
- The boxes whose confidence is lower then 0.9 are annotated separately and formated into a layer.

</em>

Steps to update the exsiting OPFs are following:

<em>

- The google ocr output are download form BDRC's S3 bucket
- The old opf is downloaded
- The ocr output is passed to updated formatted to generate new reordered opf
- The new opf files are then overwrite to old opf repo and the changes are pushed.

</em> 

#### Before Reordering

![before_karchak](https://user-images.githubusercontent.com/24893704/180758432-14d4905c-6ab8-4933-997f-3d2fdd248ea5.png)

#### After Reordering

![after_karchak](https://user-images.githubusercontent.com/24893704/180758490-e88a5ac5-2175-463f-a7a1-e67891f91571.png)

<h2 id="alternatives">Alternatives</h2>

Other solutions include:

*   Training and running text area detection models on all images in order to re-calculate the correct text order.
    - For that we need to study how to train the google ocr text area detection model. Even if we were able to pull off that, we need to re ocr 2000 something pecha which would cast us around 8-10 thousand US dollar.
*   Finding another existing OCR engine.
   - We have Transkribus but they are too expensive for us.
*   Training our own OCR models.
   - We don't have enough human resource to train our own model

<h3 id="rationale">Rationale</h3>

<em>

- The currently proposed solution is using the existing resources at fullest. Hence much cheaper than all the alternative.

</em>

<h2 id="drawbacks">Drawbacks</h2>

*The text areas which are not detected by the text area detection area of google model will be missing and can't do anything by the proposed solution.*

Example:

![improper_text_area_detection](https://user-images.githubusercontent.com/24893704/180976168-ace09271-b9a7-4d86-a25e-4af9ac64ab4a.png)

<h2 id="useful-rererences">Useful References</h2>

*Describe useful parallels and learnings from other requests, or work in previous projects.*

<em>
  
- When Transkribus was free, we were able to customize the text area detection output and send them for text recognition. This approach resulted in much better output. Here is a [blog post](https://kaldan007.github.io/blog/markdown/esukhia/2020/07/22/Transkribus.html) regarding the solution.
- Another approach is to train a model to correct ocr output like [here](https://github.com/shrutirij/ocr-post-correction).

</em>

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?
- Are there other requests with same or similar problems to solve?
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request?
- What other open requests are closely related with this request?
- Does this request depend on fulfillment of any other request?
- Does any other request depend on the fulfillment of this request?*

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

*Using such postprocessing we can prepare more training data by proofreading current pecha and re-train the model(both text area detection and recognition)*

<h2 id="infrastructure">Infrastructure</h2>

*Describe the new infrastructure or changes in current infrastructure required to fulfill this request.*

<h2 id="testing">Testing</h2>

*All the testing are done by comparing old output with script output manually and decisions are made.*

<h2 id="documentation">Documentation</h2>

*Documentations are done on code itself following google doc string convention*

<h2 id="version-history">Version History</h2>

*History of changes to this RFC. Following semantic versioning pattern and v0.1.2 for style.*

<h2 id="recordings">Recordings</h2>

*Links to audio recordings of related discussion.*

## Work Phases
<h2 id="work-phases"></h2>

<h3 id="non-coding">Non-Coding</h3>

*Keep original naming and structure, and keep as first section in Work phases section*

  - [x] Planning
  - [x] Documentation
  - [x] Testing

<h3 id="implementation">Implementation</h3>

*A list of checkboxes, one per PR. Each PR should have a descriptive name that clearly illustrates what the work phase is about.*

**Comment by ngawangtrinley** [comment]
The drawback can be solved by detecting the 4 sides of the body text area:  
1\. The topmost sides of the symbol boxes from the top lines are the top side (currently detected with your line detection algo)  
2\. The bottommost sides of the symbol boxes from the bottom lines are the bottom side  
3\. The leftmost sides of the symbol boxes from the leftmost text body column are the left side (proposed solution on pages 14 to 17 of [this document](https://docs.google.com/presentation/d/e/2PACX-1vTvAVs2Z35s-hbZrUaShwM52vOnSX1vCmGKpgFoo8l35o04a48ejM2-kczU6T2gjvONDttEO43f6ynO/pub?start=false&loop=false&delayms=3000))  
4\. The rightmost sides of the symbol boxes from the leftmost text body column are the right side  
  
Once you have the 4 sides of the body text you can include all symbol boxes comprized in the body text box and re-order them, thus solving the drawback.

**Comment by ngawangtrinley** [comment]
Done
