### ISSUE TITLE
[RFC00010] OCR Import Pipeline Scripts

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/Requests#20]
<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

*Please add ref in specified format into `RFC` title, e.g `[RFC9999]` if corresponding RFW is `[RFW9999]`.*

*Please add into this `RFC` and related `PR's` titles `[RFC_id]` e.g `[RFC_9999]`.*

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

**OCR** - Optical character recognition
**Namsel OCR** - Namsel OCR engine
**HOCR** - The output of OCRed google books. You can explore more about this format via this [link](https://en.wikipedia.org/wiki/HOCR).

<h2 id="summary">Summary</h2>

We need separate pipelines for each OCR import case. The cases we are looking for are reimporting OCR from S3, making new OPF using S3 resources,  Namsel OCR import, google vision with different google OCR engines and google HOCR import.

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

We are suggesting multiple pipelines to import OCRed Pechas as OPFs.

<em>

- **IMPORT PIPELINE**

```mermaid
flowchart TB
    linkStyle default interpolate basis
    work_id[/Work id/]
    config[/Config/]
    
    work_id --> download_images(Download Images)
    download_images -->|images_path| ocr_executor{OCR Executor}
    config --> ocr_executor

    ocr_executor -->|path| save_to_s3(Save to S3)

    save_to_s3 --> bdrc_s3[(BDRC OCR S3)]
    save_to_s3 --> completed_work[(OCRed Works Log)]

    ocr_executor -->|path| ocr_parser[[OCR Parser]]

    ocr_parser -->|pecha_path| publish_pecha(Publish Pecha)

    publish_pecha --> openpecha_repo[(OpenPecha Repository)]
    publish_pecha --> pecha_created[(Published Pechas Log)]
```

here is the pseudocode:

```python
def import_pipeline(work_id: str, config: Config):
    ocred_work_logger = Logger(config)
    published_pecha_logger = Logger(config)
    
    images_path = download_images(work_id)
    
    ocr_executor = OCRExecutor(images_path, config)
    ocr_output_path = ocr_executor.run()
    
    ocr_parser = OCRParser(ocr_output_path, config)
    pecha_path = ocr_parser.parse()
    
    save_to_s3(ocr_output_path, ocred_work_logger)
    publish_pecha(pecha_path, published_pecha_logger)
```

- **REIMPORT PIPELINE**

```mermaid
   graph TD
    A([Start]) --> B[/Pecha Id/]
    B --> C[Download old OPF]
    L[/Config/] --> C
    C -->|old opf path|D[Download OCR output from repo release]
    D -->|ocr output_path|E[[OCR parser]]
    E -->|opf path|G[Transfer new layer to old opf]
    G -->|old opf path|J[Push changes and publish to Openpecha Data]
    J --> K([End])
```

here is the pseudocode:

```python
def reimport_pipeline(pecha_id: str, config: Config):
    updated_pecha_logger = Logger(config)
    
    ocr_output_path = download_ocr_output(pecha_id)
    
    ocr_parser = OCRParser(config)
    pecha_path = ocr_parser.parse(ocr_output_path)
    
    old_pecha = download_pecha(pecha_id)
    new_pecha = OpenPechaFS(pecha_path)
    
    updated_pecha = update_pecha(old_pecha, new_pecha)
    
    publish_pecha(updated_pecha, updated_pecha_logger)
```

**NOTES**
- Since Namsel OCR output will be having its own format hence we will be needing a dedicated formatter for it.
- We need to make a helper function that can dispatch which pipeline to choose with help of work-id.

</em>

<h2 id="alternatives">Alternatives</h2>

Alternative approach would be running existing scripts responsible for sub task separately like we are doing now.

<h3 id="rationale">Rationale</h3>

<em>

- Why the currently proposed design was selected over alternatives?
   - As of now sub tasks present in pipeline are ran separately by different people. Hence we need to reach out to multiple person for an import. To make it hassle free we are proposing the pipelines.
- What would be the impact of going with one of the alternative approaches?
  - It has many dependency with multiple person and not user friendly for non technical users. 
- Is the evaluation tentative, or is it recommended to use more time to evaluate different approaches?
  - It has evaluated tentively. No need of extra time.
</em>

<h2 id="drawbacks">Drawbacks</h2>

If we make separate repo for each pipelines, it would be hard to track duplicate functions.

<h2 id="useful-rererences">Useful References</h2>

*Describe useful parallels and learnings from other requests, or work in previous projects.*

<em>
  
*   _What similar work have we already successfully completed? : No_
*   _Is this something that have already been built by others? : No_
*   _What other related learnings we have? : No_
*   _Are there useful academic literature or other articles related with this topic? (provide links) : No_
*   _Have we built a relevant prototype previously? : No_
*   _Do we have a rough mock for the UI/UX? : No_
*   _Do we have a schematic for the system? : No_

</em>

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?
  - Should we make separate repo or should we try to implement all pipeline in one repo and document it clearly? 
- Are there other requests with same or similar problems to solve?:  No_
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request?: Openpecha Toolkit as we need namsel formatter 
- What other open requests are closely related with this request?: [RCF0001](https://github.com/OpenPecha/Requests/issues/2)
- Does this request depend on fulfillment of any other request?: Yes
- Does any other request depend on the fulfillment of this request?*: YES

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

How do you see the particular system or part of the system affected by this request be altered or extended in the future.
- We can automate invoking reimport and import pipeline
- We can deploy and run these pipelines easily on a server
- We can easily add new features 

<h2 id="infrastructure">Infrastructure</h2>

*Describe the new infrastructure or changes in current infrastructure required to fulfill this request.*

<h2 id="testing">Testing</h2>

- Check whether the OPF is created in case of import pipeline in Openpecha Data
- Check whether the OPF is is update in Openpecha data in case of reimport  pipeline

<h2 id="documentation">Documentation</h2>

*Describe the level of documentation fulfilling this request involves. Consider both end-user documentation and developer documentation.*

<h2 id="version-history">Version History</h2>

v.0.0.4

<h2 id="recordings">Recordings</h2>

*Links to audio recordings of related discussion.*

## Work Phases
<h2 id="work-phases"></h2>

<h3 id="non-coding">Non-Coding</h3>

*Keep original naming and structure, and keep as first section in Work phases section*

  - [ ] Planning
  - [ ] Documentation
  - [ ] Testing

<h3 id="implementation">Implementation</h3>

*A list of checkboxes, one per PR. Each PR should have a descriptive name that clearly illustrates what the work phase is about.*

**Comment by kaldan007** [comment]
![elie comment](https://user-images.githubusercontent.com/24893704/190551193-ae730383-35d2-454a-a7e6-7c5bdf3bf459.png)

**Comment by 10zinten** [comment]
@eroux yeah, the flowchart supposed to represent the generic approach to dispatch any types of ocr engine but it fails to do that. 

@kaldan007 Maybe we should use a simple box diagram with arrow because the flowchart diagram is very limited in terms of representing abstraction in the system that is quite important to design the pipeline.

**Comment by kaldan007** [comment]
@eroux  and @10zinten is the diagram much generic

**Comment by 10zinten** [comment]
> @eroux and @10zinten I have updated the diagram to much generic view. wat do you guys think?

Nice! but I think it's still not that clear.

I have created a more elaborated diagram that we can consider as our import pipeline architecture.

what you guys think?

**Comment by eroux** [comment]
yes I think there should be just one "OCR executor", from the point of view of the workflow they will all be handled the same way

**Comment by eroux** [comment]
all the OCR output (of any service, Namsel and others) can go to BDRC's s3, no problem

**Comment by 10zinten** [comment]
\`\`\`mermaid  
flowchart TB  
   linkStyle default interpolate basis  
   work\_id\[/Work id/\]  
   config\[/Config/\]  
     
   work\_id --> download\_images(Download Images)  
   download\_images -->|images\_path| ocr\_executor{OCR Executor}  
   config --> ocr\_executor

   ocr\_executor -->|path| save\_to\_s3(Save to S3)

   save\_to\_s3 --> bdrc\_s3\[(BDRC OCR S3)\]  
   save\_to\_s3 --> completed\_work\[(OCRed Works Log)\]

   ocr\_executor -->|path| ocr\_parser\[\[OCR Parser\]\]

   ocr\_parser -->|pecha\_path| publish\_pecha(Publish Pecha)

   publish\_pecha --> openpecha\_repo\[(OpenPecha Repository)\]  
   publish\_pecha --> pecha\_created\[(Published Pechas Log)\]  
\`\`\`

@eroux how about this?

**Comment by 10zinten** [comment]
@eroux, I have updated the import pipeline diagram. What do you think now?

**Comment by eroux** [comment]
I think it's good yes! what's the "OCRed works log"? It's important to keep track of it, ultimately this should be a database but in the meantime it's good to store the logs somewhere

**Comment by 10zinten** [comment]
> I think it's good yes! what's the "OCRed works log"? It's important to keep track of it, ultimately this should be a database but in the meantime it's good to store the logs somewhere

yes, it's intended for this specific purpose, tracking the progress of ocr so that we can trouble shoot the missing ocr task later on.

**Comment by eroux** [comment]
great!

**Comment by ngawangtrinley** [comment]
@ngawangtrinley review workphases
