### ISSUE TITLE
[RFC0009] Data Pipeline Manager App

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha/Requests#21]
<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

*Please add ref in specified format into `RFC` title, e.g `[RFC9999]` if corresponding RFW is `[RFW9999]`.*

*Please add into this `RFC` and related `PR's` titles `[RFC_id]` e.g `[RFC_9999]`.*

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

*Explain any new concepts introduced in this request.*

<h2 id="summary">Summary</h2>

Create a simple web application to streamline invoking data pipelines. This architecture can helps us to automate running pipelines. Currently all of OpenPecha's data pipelines are run manually and mostly on local machine, which leads to unreliable pipeline and waste of developer's time.

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

**System Diagram:**

![Pipeline Runner Service-hackerdraw (4)](https://user-images.githubusercontent.com/16164304/196677616-c6a369e7-4ef5-4b08-8789-f6f23837279f.png)

**REST API endpoints:**

GET `/api/piplines/reimport`
**Payload**:
```json
{
  "config": {
    "ocr_engine": "google_vision"
  }
}
```

**Response**:
```json
{
  "task_id": "14049663-6257-4a1f-81e5-563c714e90af"
}
```

**Database Schemas**:
```mermaid
erDiagram
    OCRTask {
        int id
        int batch_id
        string name
        string intputs
        string orc_engine
        string model_name
    }

    ReimportTask {
        int id
        int batch_id
        string input
        string parser_link
    }
    BatchTask {
        int id
        dateFormat started
        dateFormat completed
        int total_tasks
        int completed_tasks_count
        int failed_tasks_count
    }

    Task {
        int batch_id
        string input
        string celery_task_id
        dateFormat started
        dateFormat comnpleted
        string status
        string result
        string error
    }

    OCRTask ||--|| BatchTask : is
    ReimportTask ||--|| BatchTask : is
    BatchTask ||--|{ Task : has
```
<h2 id="alternatives">Alternatives</h2>

- Manually running pipeline by developer.

<h3 id="rationale">Rationale</h3>

- Why the currently proposed design was selected over alternatives?
    - Manually running pipeline is unreliable and waste of developer time.
- What would be the impact of going with one of the alternative approaches?
    - Waste of time and money.
- Is the evaluation tentative, or is it recommended to use more time to evaluate different approaches?
    - Yes

<h2 id="drawbacks">Drawbacks</h2>

- Need AWS VM instance to host the application

<h2 id="useful-references">Useful References</h2>

- [UI/UX mock](https://www.figma.com/proto/0EPlrtIBYAnagaGV0z6Omj/OpenPecha-Data-Pipeline-Manager?page-id=2102%3A533778&node-id=2104%3A533780&viewport=445%2C348%2C0.9&scaling=min-zoom)
- https://github.com/OpenPecha/Requests/issues/21#reference-level-explanation
- https://testdriven.io/blog/fastapi-and-celery
- https://www.youtube.com/watch?v=yRClWC3pYMs

<h2 id="unresolved-questions">Unresolved Questions</h2>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?
    - No
- Are there other requests with same or similar problems to solve?
    - No

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

- Which parts of the current system are affected by this request? : None
- What other open requests are closely related with this request?
    - [RFW00010](https://github.com/OpenPecha/Requests/issues/20)
- Does this request depend on fulfillment of any other request?:
    - [RFW00010](https://github.com/OpenPecha/Requests/issues/20)
- Does any other request depend on the fulfillment of this request?* : None

 
<h2 id="future-possibilities">Future possibilities</h2>

*How do you see the particular system or part of the system affected by this request be altered or extended in the future.*
- full automation on running pipeline
- non-technical person can import the text into openpecha easily

<h2 id="infrastructure">Infrastructure</h2>

*Describe the new infrastructure or changes in current infrastructure required to fulfill this request.*

- **Frontend**
    - Use [Django](https://www.djangoproject.com) to create Frontend.
    - OCR task form (`work_ids`, `ocr_engine`, `model_type`)
    - Display a tasks status page
        - table to list tasks status (task_id, source_id, pipeline_config, status, result)

- **Backend**:
    - Use [Django](https://www.djangoproject.com) to create backend.
    - [Celery](https://docs.celeryq.dev/en/stable/index.html) task function for each supported pipeline.
    - task form handler view
        - select a celery task pipeline function for given task
        - execute the task in celery worker
        - store the queued task in `tasks_created` table
        - store task result in `tasks_completed` table

- **REST API**:
    - Use [Django REST framework](https://www.django-rest-framework.org) to create REST API
    - endpoint to handle `reimport pipeline`
        - select a celery task function for reimport task
        - execute the reimport pipeline task in celery worker
        - store completed reimport task in `reimport_tasks_completed`

<h2 id="testing">Testing</h2>
- **Frontend**
    - Test for rendering form to create OCR task
    - Test for displaying tasks status page

- **Backend**:
    - Test create task form handler view
        - test selecting a celery task pipeline function for given task
        - test executing the task in celery worker
        - test storing the queued task in `tasks_created` table
        - test storing task result in `tasks_completed` table

- **REST API**:
    - Test endpoint to handle `reimport pipeline`
        - test storing completed reimport task in `reimport_tasks_completed`

<h2 id="documentation">Documentation</h2>

*Describe the level of documentation fulfilling this request involves. Consider both end-user documentation and developer documentation.*

- User Documentation:
    - Usage
   
- Developer Documentation
    - comment all the module
    - comment all classes
    - comment all methods
    - comment all functions

<h2 id="version-history">Version History</h2>

v0.0.1

<h2 id="recordings">Recordings</h2>

None

## Work Phases
<h2 id="work-phases"></h2>

<h3 id="non-coding">Non-Coding</h3>

*Keep original naming and structure, and keep as first section in Work phases section*

  - [ ] Planning
  - [ ] Documentation
  - [ ] Testing

<h3 id="implementation">Implementation</h3>

**[Frontend + Models](https://github.com/OpenPecha/Data-Pipeline-Manager/pull/7)**
- [x] create create OCR task form (`work_ids`, `ocr_engine`, `model_type`)
- [x] Test for rendering form to create OCR task
- [x] Create BatchTask and Task model
- [x] Create Dashboard page
- [x] Display a tasks status page
    - [x] table to list tasks status (task_id, source_id, pipeline_config, status, result)
- [x] Test for displaying tasks status page
- [x] create Task detail page
- [x] Test Task detail page

**Setup Celery Task Mangement**
- [x] create Celery task function for each supported pipeline.
- [x] create task form handler view
    - [x] select a celery task pipeline function for given task
    - [x] execute the task in celery worker
    - [x] update task's status and completion date
    - [x] store pipeline results in database
- [x] Test create task form handler view
    - [x] test executing the task in celery worker
    - [x] test storing the queued task in `tasks_created` table
    - [x] test storing task result in `tasks_completed` table

**[ocr-pipeline integration](https://github.com/OpenPecha/Data-Pipeline-Manager/pull/19)**
- [x] create ocr-pipeline import config
- [x] add ocr-pipeline support in `PipelineRunner`.
- [x] dispatch ocr-pipeline function to celery worker.

<h3 id="documentation">Documentation</h3>

- [x] User Documentation
    - [x] Usage
- [x] Developer Documentation
    - [x] comment all the module
    - [x] comment all classes
    - [x] comment all methods
    - [x] comment all functions

**Comment by 10zinten** [comment]
@eroux can you comment on this when you have the time?

**Comment by eroux** [comment]
I think this is really good!

**Comment by ngawangtrinley** [comment]
@eroux just shared this good news: https://upload.bdrc.io/workspace/#/

@eroux how can we get the (temporary?) work IDs of user contributions?

**Comment by eroux** [comment]
oh this will just upload files, it won't create work IDs automatically, there should be a separate process for that. I'm not quite sure how best to handle this, but here's an idea:
- it's fairly easy to create a work id through an API call to the editor server, that's done already
- once the ID has been created, this interface could be used and the user could be instructed to upload his files to a specific directory named after the ID. Or even better, there could be an upload facility on OP that would in turn just upload to this new mechanism, but that's much more difficult to do
