### ISSUE TITLE
[RFC0012] Work File Creation(Text Instance Search)

### ISSUE THREAD

**Issue by jungtop** [OpenPecha/Requests#26]
<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

[RFC0012] Work File Creation(Text Instant Search)

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

- Work
- Instance

<h2 id="summary">Summary</h2>

To find the text instances from BDRC Archive and create work file but first we will create work file for all the work ids of nalanda text ids parsing the below csv.
[idtowork.csv](https://github.com/OpenPecha/Requests/files/10029821/idtowork.csv)

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

![work creation pipeline](https://user-images.githubusercontent.com/43548581/196150107-75496c8b-a270-4df3-82a4-c27d87788ef5.png)

<h3>Pipeline to create work file</h3>

- Get bdrc work id using title.
- Parse work info from https://purl.bdrc.io/query/graph/OP_info?R_RES=bdr:<bdrc_work_id>&format=ttl.
- Get all the instance ids.
- Find instance opf and related collection opf using openpecha data catalog.
- Publish the work to work repo.

<h2 id="alternatives">Alternatives</h2>

Searching instances using text similarity algorithms. For instances Full Text Fuzzy Search, Vector similarity, etc.

<h3 id="rationale">Rationale</h3>

<em>
- Why the currently proposed design was selected over alternatives?
  - The alternative approaches are resource and compute expensive.
  - Scope of search is limited to openpecha data.
- What would be the impact of going with one of the alternative approaches?
  - Work file creation would take lot of time and instances which are not present in openpecha data will be miss.
- Is the evaluation tentative, or is it recommended to use more time to evaluate different approaches?: No
</em>

<h2 id="drawbacks">Drawbacks</h2>

Since propose approach is highly dependent on BDRC meta data.If wrong instance is mapped in BDRC meta, it will be reflected on the work file.

<h2 id="useful-references">Useful References</h2>

<em>
- What similar work have we already successfully completed?: No
- Is this something that have already been built by others?: No
- What other related learnings we have?: None
- Are there useful academic literature or other articles related with this topic? (provide links): None
- Have we built a relevant prototype previously?: No
- Do we have a rough mock for the UI/UX?: No
- Do we have a schematic for the system?: [Reference-Level Explanation](#reference-level-explanation)

</em>

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?: None
- Are there other requests with same or similar problems to solve?: No
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request?: None
- What other open requests are closely related with this request?: None
- Does this request depend on fulfillment of any other request?: None
- Does any other request depend on the fulfillment of this request?*: None

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

will help with new work acquisitions and instances update to the work yml

<h2 id="infrastructure">Infrastructure</h2>

- Work Class
   - get work_id from title
   - heck if work is present
   - get work object
- Instance Class
  - get instances of work
  - get instance object
  - set instance or update instance

<h2 id="testing">Testing</h2>
-  Works
   - get work_id from title
   - check if work is present
   - get work object
- Instances
  - get instances of work
  - get instance object
  - set instance or update instance
 
<h3 id="Documentation">Documentation</h3>

Developer-Documentation
- Works
   - get work_id from title
   - check if work is present
   - get work object
- Instances
  - get instance
  - get instance object
  - set instance
  
<h2 id="documentation">Documentation</h2>

*Describe the level of documentation fulfilling this request involves. Consider both end-user documentation and developer documentation.*

<h2 id="version-history">Version History</h2>

v 0.0.4

<h2 id="recordings">Recordings</h2>

NA

## Work Phases
<h2 id="work-phases"></h2>

<h3 id="non-coding">Non-Coding</h3>

  - [x] Planning
  - [x] #59
  - [ ] Testing

<h3 id="implementation">Implementation</h3>

- [x] Create the works model in the toolkit
     - Assign : @jungtop 
     - Time Estimation : 12 hours
     - Time taken : 
- [x] Parse work meta from BDRC API `https://purl.bdrc.io/query/graph/OP_info?R_RES=bdr:<bdrc_work_id>&format=ttl`
    - [x] Id(str)
    - [x] Title(str)
    - [x] Alt titles(list(str))
    - [x] author(list(str))
    - [x] bdrc_work_id(str)
    - [x] instances ids
      - Assign : @ta4tsering.
      - Time Estimation : 12 hours.
      - Time Taken : 
- [x] Get Intances meta.
   - [x] Id(str)
   - [x] Title(str)
   - [x] Bdrc_instance_id(str)
   - [x] source_meta(dict)
     - Assign : @ta4tsering . 
     - Time Estimation : 8 hours.
     - Time Taken : 
- [x] Find instance opf and related collection opf using openpecha data catalog.
   - Assign : @jungtop.
   - Time Estimation : 8 hours.
   - Time Taken : 
- [x] Publish the work to work repo.
   - Assign : @jungtop 
   - Time Estimation :  8 hours.
   - Time Taken : 
- [x] Pipeline Integration.
   - Assign : @jungtop 
   - Time Estimation :  8 hours.
   - Time Taken : 

<h3 id="Testing">Testing</h3>

- [x] Works
   - [x]  get work object
- [x]  Instances
  - [x] get instance of work
  - [x] get instance object
  - [x] set instance or update instance
- [x]  Test Data
      - Assign : @ta4tsering.
      - Time Estimation : 16 hours.
      - Time Taken : 
 
<h3 id="Documentation">Documentation</h3>

Developer-Documentation
- [x] Works
   - [x]  get work object
- [x]  Instances
  - [x] get instances of work
  - [x] get instance object
  - [x] set instance or update instance

**Comment by eroux** [comment]
After discussing it with NT, this will be done in a UI that will display search results in works based on a keyword. The good news is that we have created a mechanism just for that in our editor, and we can reuse it here. The workflow to us it is:
- open an iframe on a special URL of BUDA that will display the search results
- the user clicks on the result they want
- instead of opening the record, the iframe sends a [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to the main window with some information about the result
- the main window now has the result and can close the iframe

I'm not sure the format of the message, the URLs, etc. are documented yet, but we have some code that do this in [this file](https://github.com/buda-base/rdf-document-editor/blob/main/src/containers/BUDAResourceSelector.tsx) (although not especially easy to reuse as is).

The next step will be to allow users of this interface to indicate duplication in the works. We have a UI for that but it's not wired yet, this is something I need to work on next week. pinging @berger-n just FYI

**Comment by eroux** [comment]
here's a first draft of the documentation, it should be more than enough to start:

https://github.com/buda-base/public-digital-library/blob/master/API.md

**Comment by ngawangtrinley** [comment]
Not reviewed yet
