### ISSUE TITLE
[RFW0098] Adding a Social Media Share Button option for Monlam AI Model Outputs 

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/Requests#342]
# RFW0098: *Adding a Social Media Share Button option for Monlam AI Model Outputs*

## Named Concepts
AI (Artificial Intelligence) models: are computational systems that are designed to perform tasks that typically require human intelligence. These models are based on algorithms and can learn from data, making them capable of solving a wide range of problems.

Machine Translation (Tibetan ↔ English): This is a type of language translation automation that uses AI to translate text or spoken words from Tibetan to English and vice versa. 

Text to Speech (Tibetan): Text to Speech (TTS) technology converts written text in Tibetan into spoken words.TTS systems analyze the text, synthesize the Tibetan language phonetics, and produce a spoken rendition of the text in a natural-sounding Tibetan voice.

Speech to Text (Tibetan): Speech to Text technology converts spoken words in Tibetan into written text. This involves analyzing the speech audio and accurately transcribing it into text format. 

OCR technology is used to convert different types of documents, such as scanned paper documents, PDFs, or images captured by a digital camera, into editable and searchable data. 

## Summary
Need for button for sharable link for AI model outputs in monlam ai webapp.

## Context:

Monlam AI web application currently hosts four distinct AI models:
 i)Machine Translation (Tibetan<->English) 
ii)Text to Speech (Tibetan)
iii)Speech to Text (Tibetan)
iv)OCR(Optical Character Recognition).(Tibetan)
- Each model is accessed via a separate page.
- The web application already features buttons for following the official Monlam AI social media accounts (Facebook, Instagram, Twitter).

- Social Media Sharing Buttons: Implement a button on each AI model's page for users to share a link on various social media platforms that redirects to an web page that shows the input and output of the model with only view option. In that UI it should contain a button that will redirects to monlam ai webapp to try various ai models.
- Cross-Platform Support: Compatible with multiple social media platforms.

#### Thing to remember.
- Currently the OCR model is not ready to use.

## Expected Output
The result should be a sharable link that redirects to the output of model(view only). 
Below is an expected output for MT model.
![MT](https://github.com/OpenPecha/Requests/assets/52460417/0f6f1cf3-e464-4d37-a227-259b9bb02bb4)

## Input
Include a straightforward share button on each page hosting an AI model, offering users the choice of their preferred social media platform.

## Expected Timeline
*You need to mention the expected time line you want.*

## References
Below is link for monlam webapp.
https://monlam.ai/

**Comment by tenkus47** [comment]
the staging has complete implementation of social media share button
