### ISSUE TITLE
[RFW0096]  Editable Inferences for Review and Training Data Enhancement

### ISSUE THREAD

**Issue by TenzinGayche** [OpenPecha/Requests#345]
# RFW0096:  Editable Inferences for Review and Training Data Enhancement

## Named Concepts
**"Inference output"** : refers to the results or predictions generated by an artificial intelligence (AI) model based on the input it receives.

## Summary
Many users on our websites are getting results that aren't always what they expected or are incorrect. What if we allow them to edit and submit these results? This way, we can gather valuable new data for free, and the computing resources used for generating these results can be put to good use. we need this interface for stt and mt only.

## Input
Existing website [Monlam.ai](www.monlam.ai)

## Expected Output
The new website has a feature that allows users to modify and submit their results, Which aims to collect valuable user-generated data for improvement. That not only enhances user experience but also makes effective use of computing resources involved in generating these results.

![image](https://github.com/OpenPecha/Requests/assets/24893704/ecc08843-7ae3-4bc6-b811-8b31f09c184f)

![image](https://github.com/OpenPecha/Requests/assets/24893704/8d68c43f-9883-432a-8902-dfe4b079a9e0)

## References
[Monlam.ai](www.monlam.ai)
https://www.bing.com/translator (similar)

**Comment by ta4tsering** [comment]
there should be a mockup before making changes in the UI
