### ISSUE TITLE
[RFW0109] All the inputs or inferences of Monlam AI Model need to be stored

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Requests#353]
# RFW0109: *All the inputs or inferences of Monlam AI Model need to be stored*

## Named Concepts
AI(Artificial Intelligence) Model : A program that has been trained on a set of data to recognize certain patterns or make certain decisions without further human intervention.
Inputs : Data that are input by the user when using Monlam AI models.
Inferences : Output data that are produced by the Monlam AI models.

## Summary
Monlam AI webpage consist four different models : 
1. Machine Translation :
2. Text to Speech :
3. Speech to Text : 
4. OCR :

At the moment all the inputs data by the user and output data by the models are not stored. So, storing all these data in our database could be useful.

Reason to store data : 
1. Model Improvement and Training: By analyzing user inputs and model outputs, AI researchers and developers can identify patterns, learn from mistakes, and continually improve the model's accuracy and efficiency.
2. Personalization: Stored data can be used to tailor the AI experience to individual users. By understanding a user's previous interactions, preferences, and needs, the AI can offer more relevant and personalized responses in future interactions.
3. Quality Assurance and Error Correction: By reviewing past inputs and outputs, developers can identify and correct errors in the AI's responses. This ongoing process of quality assurance helps in maintaining a high standard of accuracy and reliability.

## Input
existing website

## Expected Output

Data to be store:
- input
- output
- response time
- user_id
- model_type
- model_version
- rating

## Expected Timeline
*You need to mention the expected time line you want.*

## References
*Include all the relevent references.*

**Comment by ta4tsering** [comment]
please mention what are the data and how are we gonna store it like, I was thinking maybe we could store it in database with a three column id, input, inference and user id. so that means we should have something like this for desired output

**Comment by kaldan007** [comment]
Improved output data from AI model: what u mean by this.
