### ISSUE TITLE
RFW0121: Test MMS 

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/Requests#365]
# RFW0121: Test MMS

## Summary
We need to test Massive multilingual speech for the betterment of the model

## Key Concepts

MMS: massive multilingual speech
LM: language model
[wav2vec 2.0](https://ai.facebook.com/blog/wav2vec-20-learning-the-structure-of-speech-from-raw-audio/): This is a speech model that accepts a float array corresponding to the raw waveform of the speech signal.

## Context

In the Massively Multilingual Speech (MMS) project, we overcome challenges by combining [wav2vec 2.0](https://ai.facebook.com/blog/wav2vec-20-learning-the-structure-of-speech-from-raw-audio/)

here we use different LMs used in multiple languages.

## Outputs
Do a comparative study between MMS and Wav2Vec2,  Whisper Small, and find the tradeoffs of accuracy computational load, and training data appetite.

## Inputs
large number of labeled datasets.

## Timeline
Specify the expected delivery date for the project.

## References
[wav2vec 2.0](https://ai.facebook.com/blog/wav2vec-20-learning-the-structure-of-speech-from-raw-audio/)
[MMS](https://huggingface.co/blog/mms_adapters)

**Comment by kaldan007** [comment]
output should be comparative report of mms and current model liek wav2vec and whisper small

**Comment by tenzin3** [comment]
is the challenges here refering to "hallucination" or are there any other challenges in the current model?
