### ISSUE TITLE
[RFC0002] hOCR parser

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/Requests#8]
<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

[RFC0002] hOCR parser

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

- **BDRC S3** - Google Books OCR output is stored as received (hocr response) in an AWS S3.
- **HTML file Response** - The output of Google Books OCR is HTML file which contains the bbox co-ordinates, OCRcondifence, language and pagination for each text.
- **OPF** - Openpecha Format is the format in which we will convert the google books
  -   **base** - it will contain all base text of a volume
  -   **Layer** - it will have pagination, OCRconfidence and language layers each for respective base text.
  -   **meta** - meta will have source_metadata from the bdrc.io

<h2 id="summary">Summary</h2>

BDRC will get a lot of OCR from Google in [hocr](https://en.wikipedia.org/wiki/HOCR) format. The files will be available on s3 just like the json files we currently have. Creating opf files from these will require parsing hocr. we have to create a parser or use a hocr-parser already available to parse the HTML file to create the opf (taking reference from google OCR formatter)
<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

In order to fulfil the request, we have to update our [Openpecha toolkit hOCR formatter](https://github.com/OpenPecha/Toolkit/blob/fix-hocr-parser/openpecha/formatters/hocr.py). We need to take the refernce from [Openpecha toolkit google OCR formatter](https://github.com/OpenPecha/Toolkit/blob/master/openpecha/formatters/google_ocr.py)

Steps to parse and create_opf from the hocr output
<em>

- Download the base directory from the aws s3. Example ```s3://ocr.bdrc.io/Works/83/W2PD17457/```
- instead of having json files, the ocr output for each image is a .txt file (that I think we should ignore) plus an .html file in hocr format
- Creating opf files from these will require parsing hocr. There are tools available for this in Python, such as https://github.com/jlieth/hocr-parser as well as making changes to it as per our needs
- for source_metadata we  can use [buda from toolkit ](https://github.com/OpenPecha/Toolkit/tree/fix-hocr-parser/openpecha/buda)
- parse the html to create the opf like googl_ocr formatter
</em>

<h2 id="alternatives">Alternatives</h2>

there are no alternative for hocr formatter to openpecha format but we do have google ocr formatter [RFC0001] request that is similar to this [RFC0002] request.

<h3 id="rationale">Rationale</h3>

- the current formatter available is google ocr fomatter which parse a json file but since hocr is in html, so we can't use google ocr formatter to parse the html.
- hocr having its own formatter will be lot easier to use when we recurrently run to import google books into openpecha etext.

<h2 id="drawbacks">Drawbacks</h2>

as per the current steps it will take a lot of time to download the whole google books before parsing as for some there are 200 volumes.

<h2 id="useful-references">Useful References</h2>

Describe useful parallels and learnings from other requests, or work in previous projects.

- What similar work have we already successfully completed?
  - [RFC0001](https://github.com/OpenPecha/Requests/issues/2)
- Is this something that have already been built by others?: No
- What other related learnings we have? No
- Are there useful academic literature or other articles related with this topic? (provide links): No
- Have we built a relevant prototype previously?
  - [hocr formatter](https://github.com/OpenPecha/Toolkit/blob/fix-hocr-parser/openpecha/formatters/hocr.py)
- Do we have a rough mock for the UI/UX?: No
- Do we have a schematic for the system?: No

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?: None
- Are there other requests with same or similar problems to solve?: None
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request?: toolkit/openpecha/formatter
- What other open requests are closely related with this request?: [RFC0001]
- Does this request depend on fulfillment of any other request?: No
- Does any other request depend on the fulfillment of this request?*: No

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

<h2 id="infrastructure">Infrastructure</h2>

<h2 id="testing">Testing</h2>

- Test inputs
   - Input Type 1
       - we will use work_id : W2PD17457, this google_books output is one html file per pages.
       - we will have first two volume of the W2PD1745 with 10 page's html to parse
   - Input Type 2
       - We will use work_id: W22084, this google books output that has one html file per volume 
       - We will have first volume's html file with only few pages info in the html

- Test expected output opf
     - base folder with base text
     - layer folder with
         - Pagination.yml
         -  Language.yml
         -  OCRConfidence.yml
     - meta.yml

<h2 id="documentation">Documentation</h2>

- Developer Documentation
   
   - Parser 
     - parse the Bbox from html 
     - parse the OCRConfidence from html
     - parse the Language from html
     - parse the info for the image reference and hocr file relation
   
   - formatter
      - format the parsed book to openpecha format 

<h2 id="version-history">Version History</h2>

version 0.0.2

<h2 id="recordings">Recordings</h2>
  NA

## Work Phases
 
<h3 id="non-coding">Non-Coding</h3>

*Keep original naming and structure, and keep as first section in Work phases section*

  - [x] Planning
  - [x] Documentation
  - [x] Testing

<h3 id="implementation">Implementation</h3>

- [x] Download the base directory from the aws s3. Example ```s3://ocr.bdrc.io/Works/83/W2PD17457/```
   - [x] Download three volumes with 10 pages each to create the parser
   - [x] from the output folder in the download go through the files and parse the html files
- [x] parse the hocr file 
   - [x] parse the vertices info from html file for bbox
   - [x] parse the language info from the HTML for Language.yml
   - [x] parse the OCRConfidence which is between 1 to 100 and convert it into float value between 0 to 1 for OCRConfidence.yml
   - [x] parse the ```google_books/batch_2022/info/work_id-image_group_id/gb-bdrc-map.json``` to get the image reference and .html file relation for Pagination.yml
   - [x] parse the ```google_books/batch_2022/info.json``` to get the ocr_import_info
      
- [x] after creating the bbox dict with language, confidence, vertices. use it to create opf layers and base of google book 
- [x] for source_metadata we  can use [buda from toolkit ](https://github.com/OpenPecha/Toolkit/tree/fix-hocr-parser/openpecha/buda)

<h2 id="documentation">Documentation</h2>

- [x] Developer Documentation
   - [x] Parser 
      - [x] parse the ```google_books/batch_2022/info.json``` to get the ocr_import_info
      - [x] parse the vertices from html 
      - [x] parse the OCRConfidence from html 
      - [x] parse the Language from html
      - [x] parse the ```google_books/batch_2022/info/work_id-image_group_id/gb-bdrc-map.json``` to get the image reference and .html file realtion
      

   - [x] formatter
      - [x] use the parsed output to create opf

<h2 id="testing">Testing</h2>

- [x] Test inputs
   - [x] Input Type 1
       - [x] we use work_id : W2PD17457 as this google_books output is one html file per pages.
       - [x] we will have first two volume of the W2PD1745 with 10 page's html to parse
   - [x] Input Type 2 
      - [x] We will use work_id: [W22084](https://ia803106.us.archive.org/32/items/bdrc-W22084/bdrc-W22084-100_hocr.html), this google books output that has one html file per volume.
      - [x] #17
      
- [x] Test expected output
   - [x] test output will be an opf with
      - [x] base folder with base text
      - [x] layer folder with
         - [x] Pagination.yml
         - [x] Language.yml
         - [x] OCRConfidence.yml
      - [x] meta.yml

      
- [x] we have to pass the assert of all hocr-parser output files with the expected_output 
   - [x] assert ouput_base == expected_output  
   - [x] assert output_OCRConfidence == expected_OCRConfidence
   - [x] assert output_Pagination == expected_Pagination
   - [x] assert output_Language == expected_language
   - [x] assert output_meta == expected_meta

**Comment by eroux** [comment]
a comment on the strategy: there's no need to convert anything to json, the parser can just take each page in html, convert it into a list of BBox, and that will give you the `bounding_polys` variable of https://github.com/OpenPecha/Toolkit/blob/0f45d7cbdd1bb50656dc996a72e9fadef8cb3bf0/openpecha/formatters/google_ocr.py#L531 , and you can then use the same code as `google_ocr` (or better, make a function in google_ocr that takes this as an argument so that you can use it directly)

**Comment by eroux** [comment]
also since there will be different file organizations, there should be at least one test with the IA format (one html file per volume, although we can cut it to just a few pages), and also one test with a zip file containing a few html files

**Comment by ta4tsering** [comment]
updated the RFC to include two types of test input and also changes in the strategy as well
